<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.git.rrc</groupId>
        <artifactId>rrc-build-config</artifactId>
        <version>1.0.0</version>
        <relativePath>../rrc-config</relativePath>
    </parent>

    <artifactId>rrc-common</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>RRC Shared Libraries</name>
    <description>Reusable libraries and foundational code shared across all RRC microservices and modules.</description>

    <url>https://github.com/ramon-estravillo/workspace</url>

    <organization>
        <name>RCC Software Solutions</name>
        <url>https://rrc.example.com</url>
    </organization>

    <modules>
        <module>rrc-common-model</module>
        <module>rrc-common-system</module>
    </modules>

</project>